version: 2
jobs:
  build:
    working_directory: ~/test-circleci
    docker:
      - image: circleci/ruby:2.4-node
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_USER: circleci
          MYSQL_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: MySQL version
          command: mysql -u root -e "SELECT version();"
